export const MAX_TEXT_LENGTH = 700;

export const PROJECT_LEADERS_OPTIONS = [
  "VIKRAMM B SHROFF",
  "POOZA AGARWAL",
  "NAMMAN SHROFF",
];

export const filterOptions = {
  EDUCATION: [
    "SCHOOLS",
    "TRAINING INSTITUTIONS/CENTRES",
    "RESEARCH CENTRES",
    "COLLEGES & UNIVERSITIES",
  ],
  HEALTHCARE: ["HOSPITALS", "MEDICAL COLLEGES", "DIAGNOSTIC LABS", "CLINICS"],
  CIVIC: [
    "AUDITORIUMS",
    "TOWN HALLS",
    "POLICE STATIONS",
    "PUBLIC TOILETS & AMENITIES",
  ],
  WORKSPACE: ["GOVERNMENT OFFICES", "CORPORATE OFFICES", "RESEARCH CENTRES"],
  SPORTS: ["STADIUMS", "SPORTS COMPLEX", "MULTIPURPOSE SPORTS HALLS"],
  CULTURE: ["RELIGIOUS", "MEMORIALS", "CULTURAL COMPLEX", "MUSEUMS"],
  RESIDENTIAL: [
    "STAFF QUARTERS",
    "PRIVATE VILLAS",
    "PRIVATE APARTMENTS",
    "HOUSING",
    "HOSTELS",
    "GUEST HOUSES",
  ],
  HOSPITALITY: ["HOTELS", "RESORTS", "RESTAURANTS", "TOURISM LODGES"],
  RETAIL: [
    "SHOWROOMS",
    "SHOPPING COMPLEX",
    "DEPARTMENTAL STORES",
    "MULTIPLEXES",
  ],
};

export const TAG_OPTIONS = Object.keys(filterOptions);

export const STATES_AND_UTS = [
  "ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHHATTISGARH", "GOA",
  "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JHARKHAND", "KARNATAKA", "KERALA",
  "MADHYA PRADESH", "MAHARASHTRA", "MANIPUR", "MEGHALAYA", "MIZORAM", "NAGALAND",
  "ODISHA", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU", "TELANGANA", "TRIPURA",
  "UTTAR PRADESH", "UTTARAKHAND", "WEST BENGAL", "ANDAMAN AND NICOBAR ISLANDS",
  "CHANDIGARH", "DADRA AND NAGAR HAVELI AND DAMAN AND DIU", "DELHI",
  "JAMMU AND KASHMIR", "LADAKH", "LAKSHADWEEP", "PUDUCHERRY",
];
